default: &default
  twilio_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_number: <%= ENV['TWILIO_NUMBER'] %>

development:
  <<: *default
  secret_key_base: 5ec32edbcfa0257ca44b9ef1944318cc0e8d2b65d6a274048e5578ba203b575602b1114103d9d8b54d02197ca532e0c256812bc1fa592d6aa9ffed549151f111

test:
  <<: *default
  secret_key_base: 89b7ffbe92f27ca2ea9ccd83d48d4d49fe0b4a1499f2b8e36219e719e53153ce465db622e2e6ba84b04ea338aa137f5a6323feb5dd99402d05d4a93ec2891077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
